apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tkit-quarkus-log
  description: Logging extension for Quarkus. Provides logging interceptors and helpers
  annotations:
    gitlab.com/project-slug: 1000kit/libs/quarkus/tkit-quarkus-log
  tags:
    - java
    - quarkus
    - log
    - interceptor
    - extension
    - lib
spec:
  type: library
  lifecycle: production
  owner: 1000kit
  system: 1000kit-quarkus-libs

